name: rspecer

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        ports:
        - 3306
    container:
      image: ratovia/tech-linux
      env:
        RAILS_ENV: test
        RAILS_DATABASE_HOST: mysql
        RAILS_DATABASE_USER: root
        RAILS_DATABASE_PASSWORD: root
    steps:
    - uses: actions/checkout@v1
    
    - name: Setting
      run: |
        source /etc/profile
        rbenv rehash
        gem install bundler -v 2.0.1
        yum install -y mysql-devel
        bundle install --jobs 4 --retry 3
        bundle exec rake db:create
        bundle exec rake db:schema:load
        bundle exec rake db:seed
        bundle exec rspec
      shell: bash
