name: rspecer

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        ports:
        - 3306
    container:
      image: ratovia/tech-linux
      
    steps:
    - uses: actions/checkout@v1

    - name: Setting
      run: |
        source /etc/profile
        rbenv rehash
        ruby -v
        gem install bundler -v 2.0.1
        bundle install --jobs 4 --retry 3
      shell: bash
    
    - name: Setup Database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load
        bundle exec rake db:seed
      shell: bash
      env:  
        RAILS_ENV: test

    - name: Run rspec
      run: bundle exec rspec
      shell: bash
      env:
        RAILS_ENV: test
